
"""Shared utility helpers."""
from __future__ import annotations

import io
import logging
from typing import Any, Dict, Iterable, Optional

import pandas as pd
import streamlit as st

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s - %(message)s")


def normalize_mapping(mapping: Dict[str, Optional[str]]) -> Dict[str, str]:
    """Remove empty selections from a Streamlit column mapping."""
    return {k: v for k, v in mapping.items() if v and v != "<Not available>"}


def get_col(mapping: Dict[str, str], key: str) -> Optional[str]:
    """Return mapped dataframe column for canonical field key."""
    return mapping.get(key)


def safe_numeric(series: pd.Series) -> pd.Series:
    """Convert a series to numeric safely."""
    if series is None:
        return pd.Series(dtype="float64")
    return pd.to_numeric(series.astype(str).str.replace(",", "", regex=False).str.replace(" ", "", regex=False), errors="coerce")



def safe_datetime(series: pd.Series) -> pd.Series:
    """Convert a series to datetime safely."""
    return pd.to_datetime(series,dayfirst=True, errors="coerce")



def memory_usage_mb(df: pd.DataFrame) -> float:
    """Return dataframe memory usage in MB."""
    return float(df.memory_usage(deep=True).sum() / 1024**2)


def dataframe_info(df: pd.DataFrame) -> pd.DataFrame:
    """Create a dataframe similar to pandas info output."""
    return pd.DataFrame({
        "column": df.columns,
        "dtype": [str(t) for t in df.dtypes],
        "non_null": df.notna().sum().values,
        "nulls": df.isna().sum().values,
        "null_pct": (df.isna().mean() * 100).round(2).values,
        "unique": [df[c].nunique(dropna=True) for c in df.columns],
    })


def download_dataframe(df: pd.DataFrame, filename_stem: str = "export") -> None:
    """Render common dataframe download buttons."""
    st.download_button("Download CSV", df.to_csv(index=False).encode("utf-8"), f"{filename_stem}.csv", "text/csv")
    excel_buffer = io.BytesIO()
    with pd.ExcelWriter(excel_buffer, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Data")
    st.download_button("Download Excel", excel_buffer.getvalue(), f"{filename_stem}.xlsx", mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    st.download_button("Download JSON", df.to_json(orient="records", date_format="iso").encode("utf-8"), f"{filename_stem}.json", "application/json")


def require_columns(mapping: Dict[str, str], keys: Iterable[str]) -> bool:
    """Check whether required canonical fields are mapped."""
    missing = [k for k in keys if k not in mapping]
    if missing:
        st.warning(f"Map required fields first: {', '.join(missing)}")
        return False
    return True



def dataframe_pdf_bytes(df: pd.DataFrame, title: str = "AML Report") -> bytes:
    """Create a compact PDF preview report from a dataframe."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4))
    styles = getSampleStyleSheet()
    preview = df.head(40).astype(str)
    data = [preview.columns.tolist()] + preview.values.tolist()
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 6),
    ]))
    doc.build([Paragraph(title, styles["Title"]), Spacer(1, 8), Paragraph(f"Rows: {len(df):,} | Columns: {df.shape[1]:,}", styles["Normal"]), Spacer(1, 8), table])
    return buffer.getvalue()


def dataframe_pptx_bytes(df: pd.DataFrame, title: str = "AML Analytics Report") -> bytes:
    """Create a basic PowerPoint report with dataset summary."""
    from pptx import Presentation
    from pptx.util import Inches

    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = f"Rows: {len(df):,} | Columns: {df.shape[1]:,} | Generated by Streamlit AML app"
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = "Data Preview"
    preview = df.head(10).astype(str)
    rows, cols = preview.shape[0] + 1, min(preview.shape[1], 6)
    table = slide.shapes.add_table(rows, cols, Inches(0.3), Inches(1.2), Inches(9.0), Inches(4.5)).table
    for j, col in enumerate(preview.columns[:cols]):
        table.cell(0, j).text = str(col)
    for i, (_, row) in enumerate(preview.iterrows(), start=1):
        for j, val in enumerate(row.iloc[:cols]):
            table.cell(i, j).text = str(val)[:40]
    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue()
